on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run
        env:
           CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
           CYPRESS_INCORRECTPASSWORD: ${{ secrets.INCORRECT_PASSWORD }}
           CYPRESS_EMAILADDRESS: ${{ secrets.EMAIL_ADDRESS }}
           CYPRESS_INCORRECTEMAILADDRESS: ${{ secrets.INCORRECT_EMAIL_ADDRESS }}
           CYPRESS_TITLE: ${{ secrets.TITLE }}
           CYPRESS_DESCRIPTION: ${{ secrets.DESCRIPTION }}
           CYPRESS_CATEGORY: ${{ secrets.CATEGORY }}
           CYPRESS_CATEGORY2: ${{ secrets.CATEGORY_2 }}
           CYPRESS_ISPREMIUM: ${{ secrets.ISPREMIUM }}
           CYPRESS_IMAGEURL: ${{ secrets.IMAGE_URL }}
           CYPRESS_LOCATION: ${{ secrets.LOCATION }}
           CYPRESS_COURSEURL: ${{ secrets.COURSE_URL }}
           CYPRESS_ADDRESS: ${{ secrets.ADDRESS }}
           
