on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run
         env:
           PASSWORD: ${{ secrets.PASSWORD }}
           INCORRECTPASSWORD: ${{ secrets.INCORRECT_PASSWORD }}
           EMAILADDRESS: ${{ secrets.EMAIL_ADDRESS }}
           INCORRECTEMAILADDRESS: ${{ secrets.INCORRECT_EMAIL_ADDRESS }}
           TITLE: ${{ secrets.TITLE }}
           DESCRIPTION: ${{ secrets.DESCRIPTION }}
           CATEGORY: ${{ secrets.CATEGORY }}
           CATEGORY2: ${{ secrets.CATEGORY_2 }}
           ISPREMIUM: ${{ secrets.ISPREMIUM }}
           IMAGEURL: ${{ secrets.IMAGE_URL }}
           LOCATION: ${{ secrets.LOCATION }}
           COURSEURL: ${{ secrets.COURSE_URL }}
           ADDRESS: ${{ secrets.ADDRESS }}
           
